config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users

  resources :events
  resources :attended_events
  get '/users', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attended_events
  has_many :attendees, through: :attended_events, source: :user

  scope :upcoming, -> { where('date >= ?', Date.today) }
  scope :past, -> { where('date < ?', Date.today) }

  validates :title, presence: true
  validates :date, presence: true
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :attended_events
  has_many :attendances, through: :attended_events, source: :event

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_uniqueness_of :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attended_events_controller.rb
class AttendedEventsController < ApplicationController
  def show
    event = Event.find(params[:event_id])
    @attend = AttendedEvent.where('event_id = ?', event.id)
  end

  def create
    event = Event.find(params[:event_id])
    @attended_event = AttendedEvent.new(event_id: event.id, user_id: current_user.id)

    if AttendedEvent.where(user_id: current_user.id, event_id: params[:event_id]).exists?
      redirect_to event_path(event)
      return
    end

    redirect_to event_path(event) if @attended_event.save
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[create edit update destroy]

  def index
    @events = Event.all
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
    @event_attendees = AttendedEvent.where('event_id =?', params[:event_id])
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @event = current_user.events.build
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :date, :location, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:sign_in]

  def show
    @created_events = current_user.events
    @upcoming_events = current_user.attendances.upcoming
    @past_events = current_user.attendances.past
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attended_events_helper.rb
module AttendedEventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def attended_events
    @attended = AttendedEvent.where('user_id = ?', current_user.id)
  end
end

app/views/events/_form.htmel.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<h1>All Events</h1>
<hr>
<h2>Upcoming Events</h2>
<ul>
  <% @upcoming_events.each do |event| %>
    <li>
      <%= link_to event.title, event_path(event.id)%><br>
      <%= event.date%><br>
      <small>By - <%= event.user.email %> 
      <br>Attendees : <%= event.attendees.count %></small> 
    </li>
    <br>
  <% end %>
</ul>

<h1>Past Events</h1>
<ul>
  <% @past_events.each do |event| %>
    <li>
      <%= link_to event.title, event_path(event.id)%><br>
      <%= event.date%><br>
      <small>By - <%= event.user.email %>
      <br>Attendees : <%= event.attendees.count %></small> 
    </li>
    <br>
  <% end %>
</ul>

app/views/events/new.html.erb
<div class="d-flex border-top border-bottom p-1 mb-3">
    <div class="me-auto p-2"><%= link_to ' Back', events_path, class: "fas fa-arrow-left text-decoration-none main_cl" %></div>
</div>

<h1>New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class="d-flex border-top border-bottom p-1 mb-3">
    <div class="me-auto p-2"><%= link_to ' Back', events_path, class: "fas fa-arrow-left text-decoration-none main_cl" %></div>
</div>

<p>
  <strong>Name:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>
<hr>

<% if user_signed_in? %>
  <%= button_to 'Attend This Event', {:controller => "attended_events", :action => "create", :event_id => @event.id, :user_id=> current_user} , :method=>:post  %>
<% end %>

<hr>
<h4>Attendees</h4>
<ul>
  <% @event.attendees.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    
    <div class="container">
      <% if notice.present? %>
          <p class="alert alert-primary"><%= notice %></p>
      <% end %>

      <% if alert.present? %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-warning sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand fw-bolder" href="/" style="margin-right: 15%;">
        Private Events
    </a>

    <% if user_signed_in? %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="/events/new">Create New Event</a>
          </li>

          <li class="nav-item">
            <%= link_to ' Profile', users_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <div class="dropdown">
              <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="far fa-user"></i> <%= current_user.email %>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to ' Account Settings', edit_user_registration_path(current_user), class: "dropdown-item fas fa-cog" %></li>
              </ul>
            </div>
          </li>
      </ul>
    <% end %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <form>
        <% if current_user %>
          <%= link_to ' Log Out', destroy_user_session_path, method: :delete, class: "dropdown-item fas fa-sign-out-alt" %>
        <% else %>
          <%= link_to 'Log In', new_user_session_path, class: "btn btn-outline-success btn-sm rounded-pill m-2", style: "width: 80px" %>
          <%= link_to 'Register', new_user_registration_path, class: "btn btn-primary btn-sm rounded-pill m-2", style: "width: 80px" %>
        <% end %>
      </form>
  </div>
</nav>

app/views/users/show.html.erb
<div class="d-flex border-top border-bottom p-1 mb-3">
    <div class="me-auto p-2"><%= link_to ' Back', events_path, class: "fas fa-arrow-left text-decoration-none main_cl" %></div>
</div>

<h1>My Events</h1>
<% @created_events.each do |event| %>
<p>
  <strong>Name:</strong>
  <%= event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= event.location %>
</p>
<% end %>

<h1> Upcoming events to be attended</h1>
<% @upcoming_events.each do |attend| %>
    <p>
      <strong>Name:</strong>
      <%= attend.title %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= attend.date %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= attend.location %>
    </p>
<% end %>

<h1> Previous events attended</h1>
<% @past_events.each do |attend| %>
    <p>
      <strong>Name:</strong>
      <%= attend.title %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= attend.date %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= attend.location %>
    </p>
<% end %>